- name: AIX oslevel checking playbook
  hosts: all
  tasks:
    - name: Gather LPP Facts
      shell: "oslevel -s"
      register: output_oslevel

    - name: Print the oslevel
      debug:
        msg: "{{ ansible_hostname }} has the AIX oslevel of {{ output_oslevel.stdout }}"